config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
profiles:
  work:
    dotfiles:
      - d_nvim
      - f_tmux.conf
  work-remote:
    dotfiles:
      - d_nvim
      - f_tmux.conf
