config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_wezterm:
    src: config/wezterm
    dst: ~/.config/wezterm
profiles:
  work:
    dotfiles:
      - d_nvim
      - d_wezterm
  work-remote:
    dotfiles:
      - d_nvim
  fedora:
    dotfiles:
      - d_nvim
      - d_wezterm
  mac:
    dotfiles:
      - d_nvim
      - d_wezterm
