config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
  d_tpm:
    src: config/tmux/plugins/tpm
    dst: ~/.config/tmux/plugins/tpm
profiles:
  work:
    dotfiles:
    - d_nvim
    - f_tmux.conf
  work-remote:
    dotfiles:
    - d_nvim
    - f_tmux.conf
  dev-dsk-clujason-2b-75058408.us-west-2.amazon.com:
    dotfiles:
    - d_tpm
